apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-web-deployment
  labels:
    app: ai-web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ai-web
  template:
    metadata:
      labels:
        app: ai-web
    spec:
      containers:
      - name: model
        image: amex12/application:model
        ports:
        - containerPort: 8000
      - name: streamlit
        image: amex12/application:streamlit
        ports:
        - containerPort: 8501
---
apiVersion: v1
kind: Service
metadata:
  name: ai-web-service
spec:
  type: NodePort
  selector:
    app: ai-web
  ports:
    - protocol: TCP
      port: 8501
      nodePort: 30002
      targetPort: 8501
