name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image API
      run: docker build . --file ./model/Dockerfile --tag my-image-name:$(date +%s)
      
    - uses: actions/checkout@v3
    - name: Build the Docker image web(Streamlit)  
      run: docker build . --file ./streamlit/Dockerfile --tag my-image-name:$(date +%s)
